/**
 * Export Service - Generate and export documents
 * 
 * Supports:
 * - Markdown download (no auth required)
 * - Google Docs export (requires OAuth)
 * - Google Sheets export (requires OAuth, for parts lists)
 */

import { LessonPlan, TechnicalLessonPlan, isTechnicalPlan, Evaluation } from '../types';

// ============================================
// MARKDOWN EXPORT (No Auth Required)
// ============================================

export const downloadAsMarkdown = (
  plan: LessonPlan,
  sessionHistory?: { question: string; answer: string; evaluation: Evaluation }[]
): void => {
  const markdown = generateMarkdownContent(plan, sessionHistory);
  downloadFile(markdown, `${sanitizeFilename(plan.summary)}.md`, 'text/markdown');
};

export const generateMarkdownContent = (
  plan: LessonPlan,
  sessionHistory?: { question: string; answer: string; evaluation: Evaluation }[]
): string => {
  const isTechnical = isTechnicalPlan(plan);
  const technicalPlan = plan as TechnicalLessonPlan;

  let markdown = `# ${plan.summary}

**Mode:** ${isTechnical ? '🔧 Technical Skills' : '💬 Soft Skills'}  
**Skills:** ${plan.skillsDetected.join(', ')}  
**Educational Score:** ${plan.suitabilityScore}/100  
**Generated:** ${new Date().toLocaleDateString()}

---

## 📝 Summary

${plan.videoContext.slice(0, 1000)}${plan.videoContext.length > 1000 ? '...' : ''}

---

`;

  // Technical-specific sections
  if (isTechnical) {
    markdown += `## 📦 Parts List

| Component | Qty | Specifications | Purpose |
|-----------|-----|----------------|---------|
${technicalPlan.components.map(c => 
  `| ${c.name} | ${c.quantity || 1} | ${c.specifications || '-'} | ${c.purpose || '-'} |`
).join('\n')}

---

## 🛠️ Tools Required

${technicalPlan.tools.map(t => 
  `- ${t.required ? '**[Required]**' : '[Optional]'} **${t.name}** - ${t.purpose}${t.safetyNotes ? `\n  - ⚠️ ${t.safetyNotes}` : ''}`
).join('\n')}

---

## 📋 Build Instructions

${technicalPlan.buildSteps.map(step => `
### Step ${step.stepNumber}: ${step.title}

${step.description}

${step.tips?.length ? `**💡 Tips:**\n${step.tips.map(t => `- ${t}`).join('\n')}` : ''}

${step.safetyWarnings?.length ? `**⚠️ Safety:**\n${step.safetyWarnings.map(w => `- ${w}`).join('\n')}` : ''}

${step.checkpoints?.length ? `**✓ Verify:**\n${step.checkpoints.map(c => `- [ ] ${c}`).join('\n')}` : ''}
`).join('\n')}

---

## 🧠 Design Decisions

${technicalPlan.designDecisions.map(dd => `
### ${dd.question}

${dd.answer}

${dd.tradeoffs ? `**Tradeoffs:** ${dd.tradeoffs}` : ''}
`).join('\n')}

---

`;
  }

  // Stop Points (both modes)
  markdown += `## ❓ Practice Questions

${plan.stopPoints.map((sp, i) => `
### Question ${i + 1} (${formatTimestamp(sp.timestamp)})

**Context:** ${sp.contextSummary}

**Question:** ${sp.question}

**Rubric:** ${sp.rubric}

<details>
<summary>Reference Answer</summary>

${sp.referenceAnswer}

</details>
`).join('\n')}

---

`;

  // Session history if provided
  if (sessionHistory && sessionHistory.length > 0) {
    markdown += `## 📊 Your Session Results

${sessionHistory.map((item, i) => `
### Q${i + 1}: ${item.question}

**Your Answer:** ${item.answer}

**Score:** ${item.evaluation.score}/5 ${'⭐'.repeat(item.evaluation.score)}

**Strengths:**
${item.evaluation.strengths.map(s => `- ✓ ${s}`).join('\n')}

**Areas for Improvement:**
${item.evaluation.improvements.map(s => `- → ${s}`).join('\n')}

**Improved Answer:** ${item.evaluation.rewrittenAnswer}
`).join('\n')}

---

`;
  }

  markdown += `
---

*Generated by [SkillSync](https://skillsync.app) - Turn passive watching into active mastery.*
`;

  return markdown;
};

// ============================================
// GOOGLE DOCS EXPORT (Requires OAuth)
// ============================================

export interface GoogleDocsExportResult {
  documentId: string;
  documentUrl: string;
}

export const exportToGoogleDocs = async (
  plan: LessonPlan,
  accessToken: string,
  sessionHistory?: { question: string; answer: string; evaluation: Evaluation }[]
): Promise<GoogleDocsExportResult> => {
  // 1. Create blank document
  const createResponse = await fetch('https://docs.googleapis.com/v1/documents', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      title: `SkillSync: ${plan.summary.slice(0, 50)}`,
    }),
  });

  if (!createResponse.ok) {
    throw new Error('Failed to create Google Doc');
  }

  const doc = await createResponse.json();
  const documentId = doc.documentId;

  // 2. Build content as plain text (Google Docs API requires specific formatting)
  const content = generatePlainTextContent(plan, sessionHistory);

  // 3. Insert content
  await fetch(`https://docs.googleapis.com/v1/documents/${documentId}:batchUpdate`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      requests: [
        {
          insertText: {
            location: { index: 1 },
            text: content,
          },
        },
      ],
    }),
  });

  return {
    documentId,
    documentUrl: `https://docs.google.com/document/d/${documentId}/edit`,
  };
};

// ============================================
// GOOGLE SHEETS EXPORT (Parts List)
// ============================================

export interface GoogleSheetsExportResult {
  spreadsheetId: string;
  spreadsheetUrl: string;
}

export const exportPartsToGoogleSheets = async (
  plan: TechnicalLessonPlan,
  accessToken: string
): Promise<GoogleSheetsExportResult> => {
  // 1. Create spreadsheet
  const createResponse = await fetch('https://sheets.googleapis.com/v4/spreadsheets', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      properties: {
        title: `SkillSync Parts List: ${plan.projectType}`,
      },
      sheets: [
        {
          properties: { title: 'Parts' },
          data: [{
            startRow: 0,
            startColumn: 0,
            rowData: [
              // Header row
              {
                values: [
                  { userEnteredValue: { stringValue: 'Component' } },
                  { userEnteredValue: { stringValue: 'Quantity' } },
                  { userEnteredValue: { stringValue: 'Specifications' } },
                  { userEnteredValue: { stringValue: 'Purpose' } },
                  { userEnteredValue: { stringValue: 'Est. Cost' } },
                  { userEnteredValue: { stringValue: 'Purchased' } },
                ],
              },
              // Data rows
              ...plan.components.map(c => ({
                values: [
                  { userEnteredValue: { stringValue: c.name } },
                  { userEnteredValue: { numberValue: c.quantity || 1 } },
                  { userEnteredValue: { stringValue: c.specifications || '' } },
                  { userEnteredValue: { stringValue: c.purpose || '' } },
                  { userEnteredValue: { stringValue: c.estimatedCost || '' } },
                  { userEnteredValue: { boolValue: false } },
                ],
              })),
            ],
          }],
        },
        {
          properties: { title: 'Tools' },
          data: [{
            startRow: 0,
            startColumn: 0,
            rowData: [
              // Header row
              {
                values: [
                  { userEnteredValue: { stringValue: 'Tool' } },
                  { userEnteredValue: { stringValue: 'Required' } },
                  { userEnteredValue: { stringValue: 'Purpose' } },
                  { userEnteredValue: { stringValue: 'Safety Notes' } },
                  { userEnteredValue: { stringValue: 'Have It' } },
                ],
              },
              // Data rows
              ...plan.tools.map(t => ({
                values: [
                  { userEnteredValue: { stringValue: t.name } },
                  { userEnteredValue: { stringValue: t.required ? 'Yes' : 'No' } },
                  { userEnteredValue: { stringValue: t.purpose } },
                  { userEnteredValue: { stringValue: t.safetyNotes || '' } },
                  { userEnteredValue: { boolValue: false } },
                ],
              })),
            ],
          }],
        },
      ],
    }),
  });

  if (!createResponse.ok) {
    throw new Error('Failed to create Google Sheet');
  }

  const sheet = await createResponse.json();

  return {
    spreadsheetId: sheet.spreadsheetId,
    spreadsheetUrl: sheet.spreadsheetUrl,
  };
};

// ============================================
// HELPER FUNCTIONS
// ============================================

const formatTimestamp = (seconds: number): string => {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs.toString().padStart(2, '0')}`;
};

const sanitizeFilename = (name: string): string => {
  return name
    .replace(/[^a-z0-9\s-]/gi, '')
    .replace(/\s+/g, '-')
    .slice(0, 50)
    .toLowerCase();
};

const downloadFile = (content: string, filename: string, mimeType: string): void => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  
  URL.revokeObjectURL(url);
};

const generatePlainTextContent = (
  plan: LessonPlan,
  sessionHistory?: { question: string; answer: string; evaluation: Evaluation }[]
): string => {
  const isTechnical = isTechnicalPlan(plan);
  const technicalPlan = plan as TechnicalLessonPlan;

  let text = `${plan.summary}\n\n`;
  text += `Mode: ${isTechnical ? 'Technical Skills' : 'Soft Skills'}\n`;
  text += `Skills: ${plan.skillsDetected.join(', ')}\n`;
  text += `Educational Score: ${plan.suitabilityScore}/100\n\n`;
  text += `---\n\nSummary\n\n${plan.videoContext.slice(0, 1000)}\n\n`;

  if (isTechnical) {
    text += `---\n\nParts List\n\n`;
    technicalPlan.components.forEach(c => {
      text += `• ${c.name} (x${c.quantity || 1}) - ${c.purpose || 'N/A'}\n`;
    });

    text += `\n---\n\nTools\n\n`;
    technicalPlan.tools.forEach(t => {
      text += `• ${t.required ? '[Required]' : '[Optional]'} ${t.name} - ${t.purpose}\n`;
    });

    text += `\n---\n\nBuild Steps\n\n`;
    technicalPlan.buildSteps.forEach(step => {
      text += `Step ${step.stepNumber}: ${step.title}\n${step.description}\n\n`;
    });
  }

  text += `---\n\nPractice Questions\n\n`;
  plan.stopPoints.forEach((sp, i) => {
    text += `Q${i + 1} (${formatTimestamp(sp.timestamp)}): ${sp.question}\n`;
    text += `Reference: ${sp.referenceAnswer}\n\n`;
  });

  if (sessionHistory && sessionHistory.length > 0) {
    text += `---\n\nYour Results\n\n`;
    sessionHistory.forEach((item, i) => {
      text += `Q${i + 1}: ${item.question}\n`;
      text += `Your Answer: ${item.answer}\n`;
      text += `Score: ${item.evaluation.score}/5\n\n`;
    });
  }

  return text;
};
