import React from 'react';
import LegalPage from '../components/LegalPage';

const TermsOfService: React.FC = () => {
  return (
    <LegalPage title="Terms of Service" lastUpdated="January 22, 2026">
      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing and using SkillSync ("the Service"), you agree to be bound by these Terms of Service. 
        If you do not agree to these terms, please do not use the Service.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        SkillSync is an educational tool that uses artificial intelligence (Google Gemini) to analyze 
        YouTube videos and generate interactive learning experiences. The Service is provided for 
        educational and informational purposes only.
      </p>

      <h2>3. AI-Generated Content Disclaimer</h2>
      <p>
        <strong>IMPORTANT:</strong> The content generated by SkillSync, including but not limited to 
        questions, answers, feedback, and study materials, is produced by artificial intelligence and 
        may contain errors, inaccuracies, or misleading information.
      </p>
      <ul>
        <li>AI-generated content should not be considered professional advice</li>
        <li>Users should verify important information from authoritative sources</li>
        <li>The Service should not be used for safety-critical decisions</li>
        <li>Technical instructions should be confirmed with official documentation</li>
      </ul>

      <h2>4. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, SKILLSYNC AND ITS CREATORS SHALL NOT BE LIABLE FOR:
      </p>
      <ul>
        <li>Any direct, indirect, incidental, special, or consequential damages</li>
        <li>Loss of data, profits, or business opportunities</li>
        <li>Personal injury or property damage resulting from use of the Service</li>
        <li>Errors or omissions in AI-generated content</li>
        <li>Actions taken based on information provided by the Service</li>
      </ul>

      <h2>5. User Responsibilities</h2>
      <p>Users agree to:</p>
      <ul>
        <li>Use the Service only for lawful purposes</li>
        <li>Not attempt to reverse engineer or exploit the Service</li>
        <li>Verify AI-generated content before acting on it</li>
        <li>Take responsibility for their own learning and decisions</li>
        <li>Respect intellectual property rights of video content creators</li>
      </ul>

      <h2>6. Intellectual Property</h2>
      <p>
        SkillSync does not claim ownership of the YouTube videos analyzed. Users are responsible 
        for ensuring they have the right to use the videos for educational purposes. The Service 
        only processes publicly available content.
      </p>

      <h2>7. Service Availability</h2>
      <p>
        The Service is provided "as is" without warranties of any kind. We do not guarantee 
        uninterrupted access, and the Service may be modified or discontinued at any time.
      </p>

      <h2>8. Third-Party Services</h2>
      <p>
        SkillSync uses third-party services including Google Gemini API and YouTube. Use of these 
        services is subject to their respective terms and policies.
      </p>

      <h2>9. Changes to Terms</h2>
      <p>
        We reserve the right to modify these terms at any time. Continued use of the Service 
        after changes constitutes acceptance of the new terms.
      </p>

      <h2>10. Contact</h2>
      <p>
        For questions about these Terms of Service, please contact us through the project's 
        GitHub repository.
      </p>

      <div className="mt-8 p-4 bg-amber-50 border border-amber-200 rounded-lg">
        <p className="text-sm text-amber-800">
          <strong>Hackathon Project Notice:</strong> SkillSync is a project built for the Google 
          Gemini 3 Hackathon 2026. It is provided as a demonstration and educational tool.
        </p>
      </div>
    </LegalPage>
  );
};

export default TermsOfService;
